### ISSUE TITLE
No Texture for Mechanical Belts

### ISSUE THREAD

**Issue by CilliePaint** [GreateBeyondTheHorizon/Greate#13] opened 2023-11-22 18:44 UTC
When placing a Mechanical Belt of any type on a Shaft, it appears to have a Missing Texture.

Love the Mod btw, can't wait to see what it becomes!

**Comment by Electrolyte220** [comment] 2023-11-22 21:05
Hi, thanks for the report.

I'm going to need some more information from you:
1. What version of forge/fabric are you using?
2. What version of Greate are you using?
3. What are the steps to reproduce this?

Thanks.

**Comment by Electrolyte220** [comment] 2024-01-14 03:36
Closing due to lack of info.

**Closed as not planned by Electrolyte220** 2024-01-14 03:36 UTC
